name: result
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '^2.8.1'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_lint:
    git:
      url: git@github.com:aaazlkm/dart_lint.git
      ref: v2.0.1
  build_runner: ^2.1.7
  freezed: ^1.1.0

flutter:

