name: result
description: Resultライブラリ
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_lint:
    git:
      url: git@github.com:aaazlkm/dart_lint.git
      ref: v2.0.3
  build_runner: ^2.5.4
  freezed: ^3.1.0

flutter:

scripts:
  # formatする
  format: .fvm/flutter_sdk/bin/dart fix --apply
  # analyzeする
  analyze: fvm flutter analyze . --no-fatal-infos
  # cache削除
  clean: fvm flutter clean
  # test実行
  test: fvm flutter test
  # ビルドする
  buildRunner: fvm flutter pub run build_runner build
  # キャッシュ削除してビルドする
  buildRunnerDelete: fvm flutter pub run build_runner build --delete-conflicting-outputs
  # アセット系生成 プロジェクト初期化時に呼ぶ必要ある
  assetGen: fluttergen -c pubspec.yaml
  # indexGeneratorを実行する
  indexGenerator: dart pub global run index_generator
